### ISSUE TITLE
YAML errors

### ISSUE THREAD

**Issue by Maesto** [jreinert/autopass#3] opened 2015-08-24 14:14 UTC
With this file:

```
PASSWORDIWONTTELLYOU

---
user: username
autotype: [user, :tab, pass]
```

I get this error message.

```
Failed parsing yaml of entry 'foo.bar.baz':

---
user: username
autotype: [user, :tab, pass]
(<unknown>): did not find expected node content while parsing a flow node at line 3 column 18
/usr/bin/autopass:205:in `entry_from': undefined method `merge' for nil:NilClass (NoMethodError)
        from /usr/bin/autopass:224:in `block in update_cache'
        from /usr/bin/autopass:222:in `each'
        from /usr/bin/autopass:222:in `update_cache'
        from /usr/bin/autopass:161:in `initialize'
        from /usr/bin/autopass:251:in `new'
        from /usr/bin/autopass:251:in `<main>'
```

**Comment by repomaa** [comment] 2015-08-24 14:23
This isn't valid yaml. The problem is the colon in front of tab. If i remember correctly this used to work and would have returned the array ["user", ":tab", "pass"]. I might be wrong though.

To fix the issue you have two options:
1. Use the syntax `autotype: user :tab pass` (whitespace delimited string)
2. Use the syntax `autotype: [user, ':tab', pass]`

Will close the issue as soon as I've updated the readme

**Closed as completed** 2015-08-27 13:10 UTC
Labels: wontfix
